name: portfolio

services:
  web:
    build: .
    container_name: portfolio-web
    ports:
      - "8090:80"
    restart: unless-stopped
    networks:
      - lifeplan-net

networks:
  lifeplan-net:
    external: true
